sudo: false
language: scala
scala:
  - 2.12.6
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - openjdk10
  - openjdk11
  - oraclejdk-ea
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
